# Generated by Django 3.2.4 on 2021-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='projects-img')),
                ('github_link', models.URLField(max_length=500)),
                ('site_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
